// examples/react-router/src/pages/Parameters.jsx
import * as m from '../paraglide/messages.js';

function Parameters() {
  return (
    <div className="page">
      <h2>{m.parameters_title()}</h2>
      <p>{m.parameters_content()}</p>
      <p>{m.greeting({ name: 'Alice' })}</p>
      <p>{m.greeting({ name: 'Bob' })}</p>
      <p>{m.greeting({ name: 'Charlie' })}</p>
      <p>{m.description()}</p>
    </div>
  );
}

export default Parameters;

// examples/sveltekit-vite-6/src/routes/parameters/+page.svelte
<script>
  import * as m from '$lib/paraglide/messages.js';
</script>

<style>
  .page {
    line-height: 1.6;
  }

  h2 {
    font-size: 2em;
    margin-top: 0;
  }

  p {
    font-size: 1.2em;
  }
</style>

<div class="page">
  <h2>{m.parameters_title()}</h2>
  <p>{m.parameters_content()}</p>
  <p>{m.greeting({ name: 'Alice' })}</p>
  <p>{m.greeting({ name: 'Bob' })}</p>
  <p>{m.greeting({ name: 'Charlie' })}</p>
  <p>{m.description()}</p>
</div>
